### PR TITLE
Adjusted Readme.md to look a bit more trustable and brightly branded

### PR DESCRIPTION
**Pull request by PixelsCommander**

### CODE REVIEW

**Comment by RevillWeb** [comment]
Absolutely love the logo! Do you have the source files for it? I'd love to make a few changes such as colour etc before I merge.

**Comment by PixelsCommander** [comment]
Ah, not sure, it was a modification of some NO PASARAN! poster. You may
find it here
https://www.google.nl/search?q=no+pasaran&espv=2&biw=1602&bih=1273&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiP26bJo4TOAhXiJcAKHSFeCZ0Q_AUIBigB&dpr=1#imgrc=_
also changing color is possible with HUE / SATARUATION in Photoshop (cmd +
u)

2016-07-21 11:46 GMT+02:00 Leon Revill notifications@github.com:

**Comment by RevillWeb** [comment]
Brilliant thanks. I'll throw it in PhotoShop and have a play around.

**Comment by RevillWeb** [comment]
I've merged your pull request and made a few changes including a new logo, what do you think?

**Comment by PixelsCommander** [comment]
Logo is awesome. The thing I am worried a bit that we have too much text
which is boring for a newcomer. Should we play just a sentance on top of
readme and give a code example then?

2016-07-21 21:32 GMT+02:00 Leon Revill notifications@github.com:

**Comment by RevillWeb** [comment]
I see what you are saying - I will remove the description like you suggested.

**Pull request merged**
